// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVDcaATuO4W0iJ8yI_l6eBDmu7g6KiBog',
    appId: '1:949953727292:web:067d9a8103145d40332c39',
    messagingSenderId: '949953727292',
    projectId: 'neighbor-connect-b8b61',
    authDomain: 'neighbor-connect-b8b61.firebaseapp.com',
    storageBucket: 'neighbor-connect-b8b61.appspot.com',
    measurementId: 'G-GNQHS2X2SL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGoy44vZp4_05oMbvJrYZ5zS6DBlm3Qns',
    appId: '1:949953727292:android:855aed08880c3e3b332c39',
    messagingSenderId: '949953727292',
    projectId: 'neighbor-connect-b8b61',
    storageBucket: 'neighbor-connect-b8b61.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuaOcVPyV8tkWb9FQXm8ctsdXo0OicvXg',
    appId: '1:949953727292:ios:b3d2990ea9acc900332c39',
    messagingSenderId: '949953727292',
    projectId: 'neighbor-connect-b8b61',
    storageBucket: 'neighbor-connect-b8b61.appspot.com',
    iosClientId: '949953727292-77eqv2nbdt8c4keqls0fbhbbaos81gq9.apps.googleusercontent.com',
    iosBundleId: 'com.example.neighborconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuaOcVPyV8tkWb9FQXm8ctsdXo0OicvXg',
    appId: '1:949953727292:ios:a7721fe45cdf2548332c39',
    messagingSenderId: '949953727292',
    projectId: 'neighbor-connect-b8b61',
    storageBucket: 'neighbor-connect-b8b61.appspot.com',
    iosClientId: '949953727292-jgn1olakgrjrb617mbvaic30ei30aicl.apps.googleusercontent.com',
    iosBundleId: 'com.example.neighborconnect.RunnerTests',
  );
}
